# fly.toml app configuration file generated for expertify-tunnel on 2023-04-26T17:18:17+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "expertify-tunnel"
primary_region = "cdg"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  ALLOWED_HOSTS = "expertify-tunnel-svc.fly.dev,tunnel.expertify.store,expertify.store"
  BLOCKED_SUB_DOMAINS = "wormhole,dashboard,2,myapp"
  NET_PORT = "10002"
  CTRL_PORT = "10001"
  RUST_LOG = "tunnelto_server=debug"
  TUNNEL_HOST = "tunnel.expertify.store"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 10001
    handlers = ["tls", "http"]
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.http_checks]]
    interval = "10s"
    timeout = "20s"
    restart_limit = 0
    method = "get"
    path = "/health_check"
    protocol = "http"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.http_checks]]
    interval = "10s"
    timeout = "20s"
    restart_limit = 0
    method = "get"
    path = "/0xDEADBEEF_HEALTH_CHECK"
    protocol = "http"
